### ISSUE TITLE
Create tasks for creating blocks as test data

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/recipe-content-blocks#7]
To assist with testing a task should be created to add test blocks to a site. Should be a range of block types to replicate a prod-like environment.

**Comment by robbieaverill** [comment]
We can put a task like this into https://github.com/silverstripe/silverstripe-frameworktest but I wouldn't want to see it merged into this recipe

**Comment by ScopeyNZ** [comment]
I'm going to close this in favour of https://github.com/silverstripe/silverstripe-frameworktest/issues/49.
